name: DeathBan
version: 0.2
api: 4.0.0
main: godoob\deathban\DeathBan
author: godoob

commands:
  deathban:
    usage: "/deathban <ban|unban> <player> [time]"
    aliases:
      - db
    description: main command of deathban
    permission: deathban.main
    permission-message: "You don't have permission to use this command."
  
permissions:
  deathban.main:
    default: op
  deathban.noban:
    default: false